### PR TITLE
updated clear() to clear the hoard's namespace, not the entire cache

### PR DESCRIPTION
**Pull request by acr13**
Let me know what you think @SethDavenport 

I'm still not sure I 100% understand the architecture, but this feels right to clear out an entire HttpHoard.

Also I can move the semi-colon fixes to a different PR if needed.

### CODE REVIEW

**Comment by SethDavenport** [comment]
Looks good, thanks for the semicolons as well.  I need to hook up eslint at some point.

Can you write a unit test for this scenario?

**Comment by SethDavenport** [comment]
Actually on second thought - I would just change the existing `.clear()` function to do what `.clearNamespace()` does.  I don't think a hoard should expose functionality that affects other namespaces.

Since this is a API behaviour change, I'll update the version to 0.4.0 when I publish.

**Comment by acr13** [comment]
Sounds good - I'll update this to be in the `clear()` function and add some unit tests.

**Comment by acr13** [comment]
Ready for a new review @SethDavenport

**Comment by SethDavenport** [comment]
:shipit:

**Pull request merged**
